name: C/C++ CI

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest,ubuntu-20.04, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v4
    - name: install_deps
      run: bash ./.github/workflows/prepare_build.sh -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON
    - name: build
      run: make -C build/
    - name: test_def
      run: ./build/test/test_suite
    - name: test_ipc
      run: ./build/test/test_suite_ipc
    - name: test_udt
      run: ./build/test/test_suite_udt
    - name: test_gzip
      run: ./build/test/test_suite_gzip
